### ISSUE TITLE
Feat: netlify 리다이렉트

### ISSUE THREAD

**Issue by bohyemian** [FRONTENDBOOTCAMP-12th/2gether-kongtteok#133]
## Netlify 배포 오류 해결책

Netlify 배포 오류 문제를 해결하려면 리디렉션(redirects) 설정이 필요합니다.

1. 프로젝트 루트 디렉토리에 **`netlify.toml`** 파일을 작성합니다.
2. **`netlify.toml`** 파일에 다음 코드를 추가합니다.
    
    ```toml
    [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    ```
